### ISSUE TITLE
New Host/Licensee validation fails with HTTP400 - Licensee does not exist

### ISSUE THREAD

**Issue by r-brown** [Labs64/PluginPass#19]
Attempt to validate new Licensee fails with the message:
```
Fatal error: Uncaught NetLicensing\RestException: [0]: Unsupported response status code 400: Licensee with the number 'localhost' does not exist. thrown in /var/www/html/wp-content/plugins/pluginpass/vendor/labs64/netlicensingclient-php/service/NetLicensingService.php on line 169

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.
```

which is related to the Token Creation:
**request**
```
POST https://go.netlicensing.io/core/v2/rest/token
tokenType=SHOP&licenseeNumber=localhost&successURL=Acquire+licenses
```

**response**
```
400
Content-Type: application/json
{"Signature":null,"infos":{"info":[{"value":"Licensee with the number 'localhost' does not exist.","id":"NotFoundException","type":"ERROR"}]},"items":null,"id":null,"ttl":null}
```

**Comment by r-brown** [comment]
TODO: verify, that new Licensees can be auto-created upon first validation, so further methods calls won't cause such errors.

**Comment by r-brown** [comment]
TODO: add consent verification before token get request

**Comment by v-rudkovskiy** [comment]
The problem is that we use the API licensee role to validate and create the token. If we want to make sure that Licensee can be created automatically, we need to get the product (check licensee auto-create property) and get the licensee (check if it exists), but the role "licensee" doesn't have these rights (throw 403 Access Denied ).

**Comment by r-brown** [comment]
As discussed all NLIC requests should be avoided without given user consent; e.g.
- validate
- get token
- open shop

PluginPass used (developer) should be able to handle this case by requesting user consent; see also #13 

Please also update:
- PHP Doc
- Wiki

**Comment by r-brown** [comment]
Following sample code https://github.com/Labs64/PluginPass/blob/master/examples/class-pluginpass-demo-settings.php#L95 return _"No Consent"_ even after _set_consent()_ was called.

**Comment by r-brown** [comment]
@v-rudkovskiy please improve above sample, so this:
- provides a good starting point with PluginPass
- showcases PluginPass relevant exception handling

**Comment by r-brown** [comment]
Valid / not valid status mixed

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/1361258/64406831-1863d600-d083-11e9-94e4-901e10cb802f.png">
