### ISSUE TITLE
Install & activate PluginPass as dependency

### ISSUE THREAD

**Issue by r-brown** [Labs64/PluginPass#2]
Allow defining PluginPass as a dependency in other 3pp WP plugins by:
- using WP plugin repository (once approved)
- using GitHub released version

----

Describe how to in the Wiki

**Comment by v-rudkovskiy** [comment]
[wiki page](https://github.com/Labs64/PluginPass/wiki/Activate-PluginPass-as-dependency)

**Comment by v-rudkovskiy** [comment]
Have been Improved "PluginPass as dependency" sample in wiki.
Example: 
Try to activate plugin with dependency.
![Screenshot_6](https://user-images.githubusercontent.com/3775910/64344945-1c96e180-cff8-11e9-972b-d82536c66209.png)
If the plugin is not installed, a message and button for installation  appears.
![Screenshot_5](https://user-images.githubusercontent.com/3775910/64344954-20c2ff00-cff8-11e9-9c22-c1bf4e007458.png)
