### ISSUE TITLE
How To: Describe plugin usage

### ISSUE THREAD

**Issue by r-brown** [Labs64/PluginPass#4]
Describe step-by-step how to use PluginPass:
- Configure [NetLicensing product](https://netlicensing.io/)
- use https://wppb.me to create a new plugin
- provide code snippets how to:
-- define PluginPass as dependency #2 
-- initialize Plugin
-- validate
-- work with NetLicensing Validation Response

----

Publish this How To at https://github.com/Labs64/PluginPass/wiki

**Comment by v-rudkovskiy** [comment]
Added documentation on using PluginPass at [wiki](https://github.com/Labs64/PluginPass/wiki/Plugin-Configuration)

**Comment by r-brown** [comment]
Images housekeeping

<img width="1637" alt="Create Product | NetLicensing 2019-08-11 10-14-48" src="https://user-images.githubusercontent.com/1361258/63632548-c497cc80-c640-11e9-8665-b523284fdaae.png">
<img width="1635" alt="Customers | NetLicensing 2019-08-11 10-48-42" src="https://user-images.githubusercontent.com/1361258/63632549-c5306300-c640-11e9-8e89-a32568507166.png">
<img width="1638" alt="PluginPass Demo  localhost  | NetLicensing 2019-08-11 10-51-25" src="https://user-images.githubusercontent.com/1361258/63632551-c5306300-c640-11e9-9318-e1f5f02bbfcb.png">
<img width="1636" alt="PluginPass Demo  localhost  | NetLicensing 2019-08-11 10-51-56" src="https://user-images.githubusercontent.com/1361258/63632552-c5c8f980-c640-11e9-97e9-72068f0f27eb.png">
<img width="1633" alt="PluginPass Demo  P6N6UW7U4  : Plugin Subscription  MN5VYRR54  | NetLicensing 2019-08-11 10-19-01" src="https://user-images.githubusercontent.com/1361258/63632553-c5c8f980-c640-11e9-8181-787f5d2fd94b.png">
<img width="1631" alt="PluginPass Demo  P6N6UW7U4  | NetLicensing 2019-08-11 10-15-34" src="https://user-images.githubusercontent.com/1361258/63632554-c5c8f980-c640-11e9-8224-e13afcdacb9f.png">
<img width="1636" alt="PluginPass Demo  P6N6UW7U4  | NetLicensing 2019-08-11 10-48-15" src="https://user-images.githubusercontent.com/1361258/63632555-c6619000-c640-11e9-9e2f-641dc0dcb2ef.png">
<img width="1634" alt="PluginPass Demo  P6N6UW7U4  | NetLicensing 2019-08-17 09-21-05" src="https://user-images.githubusercontent.com/1361258/63632556-c6619000-c640-11e9-9584-9e6f76220963.png">
<img width="1631" alt="Products | NetLicensing 2019-08-11 10-12-55" src="https://user-images.githubusercontent.com/1361258/63632557-c6619000-c640-11e9-82ed-52ffa459986a.png">
<img width="1641" alt="Settings | NetLicensing 2019-08-11 10-36-25" src="https://user-images.githubusercontent.com/1361258/63632558-c6619000-c640-11e9-88d5-a31c522e9fb6.png">

**Comment by r-brown** [comment]
PluginPass overview


![PluginPass-overview](https://user-images.githubusercontent.com/1361258/63633320-4db60000-c64f-11e9-95e2-7de7e31dd8f0.png)

**Comment by r-brown** [comment]
PluginPass admin / pligins table
<img width="1636" alt="PluginPass ‹ PluginPass Demo — WordPress 2019-08-11 10-47-47" src="https://user-images.githubusercontent.com/1361258/63632550-c5306300-c640-11e9-823d-95af83dc10c9.png">

**Comment by r-brown** [comment]
@v-rudkovskiy reference to `pluginpass/pluginpass.php` isn't correct - please use correct PluginPass reference from the WP repository - https://wordpress.org/plugins/pluginpass-pro-plugintheme-licensing/
